"""Constants for the JVA Electric Fence integration."""

from __future__ import annotations

from homeassistant.const import CONF_HOST, CONF_PASSWORD, CONF_SCAN_INTERVAL, CONF_USERNAME

DOMAIN = "jva_electric_fence"
VERSION = "0.1.1"
DEFAULT_HOST = "http://192.168.1.50"
DEFAULT_SCAN_INTERVAL = 15
MIN_SCAN_INTERVAL = 5
MAX_SCAN_INTERVAL = 3600
MANUFACTURER = "JVA"
MODEL = "PAE212"

CONF_HOST = CONF_HOST
CONF_USERNAME = CONF_USERNAME
CONF_PASSWORD = CONF_PASSWORD
CONF_SCAN_INTERVAL = CONF_SCAN_INTERVAL
